server:
  port: 9000
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      plugin:
        config:
          log-request: true
      routes:
        - id: profile-service
          uri: lb://profile-service
          predicates:
            - Path=/api/profile/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 2
                key-resolver: "#{@requestPathKeyResolver}"
eureka:
  instance:
    preferIpAddress: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/